# <p style="text-align: center; color: red"> Learn Numpy and Empower Yourself</p>

## **Index**
0. [Introduction & Index](#-Learn-Numpy-and-Empower-Yourself)
1. [Basics](#1--Basics)    
* 1.1 - [Shape](#1.a---Shape)    
* 1.2 - [Dimensions](#1.b---Dimensions)
* 1.3 - [Type](#1.c---Type)
* 1.4 - [Size](#1.d---Size)
* 1.5 - [Other](#1.e---Other)    
2. [Array Creation](#2--Array-Creation)
* 2.1 - [Two, Three... Dimensional Arrays](#2.a---Two,-Three...-Dimensional-Arrays)
* 2.2 - [With 'dtype'](#2.b---With-'dtype')
* 2.3 - [Create Arrays With Initial Placeholder Content](#2.c---Create-Arrays-With-Initial-Placeholder-Content)
* 2.4 - ['arange' Analogous To 'range'](#2.d---'arange'-analogous-to-'range')
3. [Basic Operations](#3--Basic-Operations)
* 3.1 - [Act in Place Operators](#3.a---Act-in-Place-Operators)
* 3.2 - [Methods of ndarray Class As Unary Operations](#3.b---Methods-of-ndarray-Class-As-Unary-Operations)
* 3.3 - [Upcasting](#3.c---Upcasting)
* 3.4 - [ufuncs (Universal Functions)](#3.d---ufuncs-(Universal-Functions))
4. [Indexing, Slicing and Iterating](#4--Indexing,-Slicing-and-Iterating)

In [2]:
import numpy as np
import matplotlib as plt

## 1- Basics

In [3]:
# create an array for inspecting important attributes of an ndarray object: 
first = np.arange(15).reshape(3, 5)

In [4]:
first

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 1.a - Shape

In [5]:
# returns a tuple of integers indicating the size of the array in each
# dimension. For a matrix with n rows and m columns, shape will be (n, m).
# The length of the returned tuple is equal to the value that ndarray.ndim 
# would return.
first.shape

(3, 5)

### 1.b - Dimensions

In [6]:
# returns the number of axes (dimensions) of the array:
first.ndim

2

### 1.c - Type

In [7]:
# an object describing the type of the elements in the array:
first.dtype

dtype('int32')

In [8]:
first.dtype.name

'int32'

### 1.d - Size

In [9]:
# returns the size in bytes of each element of the array: 
first.itemsize

4

In [10]:
# returns the total number of elements of the array. This is equal to 
# the product of the elements of ndarray.shape.
first.size

15

### 1.e - Other

In [11]:
type(first)

numpy.ndarray

In [12]:
# the buffer containing the actual elements of the array:
first.data

## 2- Array Creation

In [13]:
# use 'array' function in order to form an array by giving a regular Python
# list or tuple as an argument (a single sequence):  
new = np.array([1, 2, 3])

In [14]:
print(new)
print(type(new))
print(new.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int32


In [15]:
new_2 = np.array([1.0, 2.0, 3.0])
print(new_2.dtype)

float64


### 2.a - Two, Three... Dimensional Arrays

In [16]:
# 'array' function transforms sequences of sequences into two-dimensional 
# arrays, sequences of sequences of sequences into three-dimensional arrays, 
# and so on:

two_d = np.array([(1,2), (4,5), (7,8)])
print(two_d)
print("Dimensions:", two_d.ndim)
print("Size of dimensions:", two_d.shape)

print("-----------")

three_d = np.array([[(1, 2), (3, 4)], [(5, 6), (7, 8)]])
print(three_d)
print("Dimensions:", three_d.ndim)
print("Size of dimensions:", three_d.shape)

print("-----------")

another_3d = np.array([[(0, 1), (2, 3)], [(4, 5), (6, 7)], [(8, 9), (10, 11)]])
print(another_3d)
print("Dimensions:", another_3d.ndim)
print("Size of dimensions:", another_3d.shape)

[[1 2]
 [4 5]
 [7 8]]
Dimensions: 2
Size of dimensions: (3, 2)
-----------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Size of dimensions: (2, 2, 2)
-----------
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
Dimensions: 3
Size of dimensions: (3, 2, 2)


In [135]:
# investigate the output, not the code

line_break = "\n\n<<<<<<>>>>>>\n\n"
print("another_3d:\n", 
      another_3d, 
      line_break, 
      "another_3d[0]:\n", 
      another_3d[0],
      line_break,
      "another_3d[0][0]:\n",
      another_3d[0][0],
      line_break,
      "another_3d[0][0][0]:\n",
      another_3d[0][0][0])

another_3d:
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] 

<<<<<<>>>>>>

 another_3d[0]:
 [[0 1]
 [2 3]] 

<<<<<<>>>>>>

 another_3d[0][0]:
 [0 1] 

<<<<<<>>>>>>

 another_3d[0][0][0]:
 0


### 2.b - With 'dtype'

In [18]:
# specify your desired data-type when creating an array with dtype argument:
print(np.array([1, 2, 3], dtype=complex), "\n\n", np.array([1, 2, 3], float))

[1.+0.j 2.+0.j 3.+0.j] 

 [1. 2. 3.]


### 2.c - Create Arrays With Initial Placeholder Content

In [19]:
# use 'zeros' function to create an array full of zeros:
print(np.zeros((2, 2)), end="\n\n")

# use 'ones' function to create an array full of ones:
print(np.ones((2, 3)), end="\n\n")

# use 'empty' function to create an array whose initial content is random and depends on the state 
# of the memory. 'empty' function is marginally faster than 'zeros' function but should be used 
# with caution.
print(np.empty((3,2)), end="\n\n")

[[0. 0.]
 [0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]



In [20]:
# use 'zeros_like' function to return an array of zeros with the same shape and type as a given array:
given_array = np.arange(1, 10, 4)
np.zeros_like(given_array)

array([0, 0, 0])

In [21]:
# use 'ones_like' function to return an array of ones with the same shape and type as a given array:
np.ones_like(given_array)

array([1, 1, 1])

In [22]:
# use 'empty_like' function to return a random array with the same shape and type as a given array:
np.empty_like(given_array)

array([0, 0, 0])

### 2.d - 'arange' analogous to 'range'

In [23]:
# use 'arange' function (analogous to the built-in function 'range') to create sequences of numbers:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [24]:
np.arange(1, 10, 1.5) # it accepts float arguments

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [25]:
# use 'linspace' function to return evenly spaced numbers over a specified interval:
np.linspace(1, 10, 9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [26]:
np.linspace(1, np.pi * 2, 100)

array([1.        , 1.05336551, 1.10673102, 1.16009652, 1.21346203,
       1.26682754, 1.32019305, 1.37355856, 1.42692407, 1.48028957,
       1.53365508, 1.58702059, 1.6403861 , 1.69375161, 1.74711711,
       1.80048262, 1.85384813, 1.90721364, 1.96057915, 2.01394465,
       2.06731016, 2.12067567, 2.17404118, 2.22740669, 2.2807722 ,
       2.3341377 , 2.38750321, 2.44086872, 2.49423423, 2.54759974,
       2.60096524, 2.65433075, 2.70769626, 2.76106177, 2.81442728,
       2.86779279, 2.92115829, 2.9745238 , 3.02788931, 3.08125482,
       3.13462033, 3.18798583, 3.24135134, 3.29471685, 3.34808236,
       3.40144787, 3.45481338, 3.50817888, 3.56154439, 3.6149099 ,
       3.66827541, 3.72164092, 3.77500642, 3.82837193, 3.88173744,
       3.93510295, 3.98846846, 4.04183396, 4.09519947, 4.14856498,
       4.20193049, 4.255296  , 4.30866151, 4.36202701, 4.41539252,
       4.46875803, 4.52212354, 4.57548905, 4.62885455, 4.68222006,
       4.73558557, 4.78895108, 4.84231659, 4.8956821 , 4.94904

## 3- Basic Operations

In [157]:
# Arithmetic operators on arrays apply elementwise. 
tens = np.array([10, 20, 30, 40])
ones = np.arange(4)

the_sum = tens + ones
the_sum

array([10, 21, 32, 43])

In [158]:
ones ** 2

array([0, 1, 4, 9], dtype=int32)

In [159]:
np.sin(tens) * 10

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [160]:
tens < 25

array([ True,  True, False, False])

In [161]:
the_multip = ones * tens # elementwise product

the_multip

array([  0,  20,  60, 120])

In [162]:
matrix_a = np.array([[1, 0], [0, 1]])
matrix_b = np.array([[1, 3], [8, 7]])

matrix_a @ matrix_b # matrix product

matrix_a.dot(matrix_b) # another matrix product

array([[1, 3],
       [8, 7]])

### 3.a - Act in Place Operators

In [163]:
rg = np.random.default_rng(1) # create instance of default random number generator
matrix_a = rg.random((2, 2))
matrix_b = np.ones((2, 2), dtype=int)

# some operations, such as += and *=, act in place 
matrix_b *= 3
matrix_a += matrix_b

print("Matrix B:\n----\n", matrix_b)
print("\nMatrix A:\n----\n", matrix_a)

Matrix B:
----
 [[3 3]
 [3 3]]

Matrix A:
----
 [[3.51182162 3.9504637 ]
 [3.14415961 3.94864945]]


In [166]:
matrix_b += matrix_a # since matrix_a is not automatically converted to integer type, we'll get error
matrix_b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

### 3.b - Methods of ndarray Class As Unary Operations

In [167]:
# Many unary operations, such as computing the sum of all the elements in the array, are 
# implemented as methods of the ndarray class.

matrix_a = rg.random((2, 4))
print("Matrix\n----\n", matrix_a, 
      "\n Sum:", matrix_a.sum(), 
      "\n Minimum:", matrix_a.min(), 
      "\n Maximum:", matrix_a.max(), 
      "\n Cumulative Sum:\n", matrix_a.cumsum())

Matrix
----
 [[0.31183145 0.42332645 0.82770259 0.40919914]
 [0.54959369 0.02755911 0.75351311 0.53814331]] 
 Sum: 3.840868853982877 
 Minimum: 0.027559113243068367 
 Maximum: 0.8277025938204418 
 Cumulative Sum:
 [0.31183145 0.7351579  1.56286049 1.97205963 2.52165332 2.54921243
 3.30272554 3.84086885]


In [168]:
# By default, these operations apply to the array as though it were a list of numbers, regardless
# of its shape. However, by specifying the axis parameter you can apply an operation along the 
# specified axis of an array:

matrix_a = np.arange(20).reshape(4, 5)
print("Matrix\n----\n", matrix_a, 
      "\n Sum of Each Column:", matrix_a.sum(axis=0), 
      "\n Minimum of Each Row:", matrix_a.min(axis=1), 
      "\n\n Cumulative Sum along Each Row:\n", matrix_a.cumsum(axis=1),
      "\n\n Cumulative Sum along Each Column:\n", matrix_a.cumsum(axis=0))

Matrix
----
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 
 Sum of Each Column: [30 34 38 42 46] 
 Minimum of Each Row: [ 0  5 10 15] 

 Cumulative Sum along Each Row:
 [[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]
 [15 31 48 66 85]] 

 Cumulative Sum along Each Column:
 [[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]]


### 3.c - Upcasting

In [175]:
# When operating with arrays of different types, the type of the resulting array corresponds to 
# the more general or precise one (a behavior known as upcasting)

matrix_a = np.ones(3, dtype=int)
matrix_b = np.linspace(1, 10, 3)
matrix_a + matrix_b

array([ 2. ,  6.5, 11. ])

### 3.d - ufuncs (Universal Functions)

In [200]:
# NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are 
# called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an 
# array, producing an array as output.

a = np.arange(3)

np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [201]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356])

In [202]:
np.add(a, np.sqrt(a))

array([0.        , 2.        , 3.41421356])

In [207]:
a = np.arange(10).reshape(2, 5)
np.transpose(a)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [209]:
np.mean(a)

4.5

In [210]:
np.median(a)

4.5

In [211]:
np.std(a)

2.8722813232690143

In [212]:
np.var(a)

8.25

## 4- Indexing, Slicing and Iterating