# <p style="text-align: center; color: red"> Learn Numpy and Empower Yourself</p>

## **Index**
0. [Introduction & Index](#-Learn-Numpy-and-Empower-Yourself)
1. [Basics](#1--Basics)    
* 1.1 - [Shape](#1.a---Shape)    
* 1.2 - [Dimensions](#1.b---Dimensions)
* 1.3 - [Type](#1.c---Type)
* 1.4 - [Size](#1.d---Size)
* 1.5 - [Other](#1.e---Other)    
2. [Array Creation](#2--Array-Creation)
* 2.1 - [Two, Three... Dimensional Arrays](#2.a---Two,-Three...-Dimensional-Arrays)
* 2.2 - [With 'dtype'](#2.b---With-'dtype')
* 2.3 - [Create Arrays With Initial Placeholder Content](#2.c---Create-Arrays-With-Initial-Placeholder-Content)
* 2.4 - ['arange' Analogous To 'range'](#2.d---'arange'-analogous-to-'range')
3. [Basic Operations](#3--Basic-Operations)
* 3.1 - [Act in Place Operators](#3.a---Act-in-Place-Operators)
* 3.2 - [Methods of ndarray Class As Unary Operations](#3.b---Methods-of-ndarray-Class-As-Unary-Operations)
* 3.3 - [Upcasting](#3.c---Upcasting)
* 3.4 - [ufuncs (Universal Functions)](#3.d---ufuncs-(Universal-Functions))
4. [Indexing, Slicing and Iterating](#4--Indexing,-Slicing-and-Iterating)

In [1]:
import numpy as np
import matplotlib as plt

## 1- Basics

In [39]:
# create an array for inspecting important attributes of an ndarray object: 
first = np.arange(15).reshape(3, 5)

In [40]:
first

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 1.a - Shape

In [41]:
first.shape

(3, 5)

<font size="3"> It returns a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n, m). The length of the returned tuple is equal to the value that ndarray.ndim would return.</font>

### 1.b - Dimensions

In [42]:
first.ndim

2

<font size="3">It returns the number of axes (dimensions) of the array.</font>

### 1.c - Type

In [46]:
first.dtype  # an object describing the type of the elements in the array

dtype('int32')

In [8]:
first.dtype.name

'int32'

### 1.d - Size

In [45]:
first.itemsize  # returns the size in bytes of each element of the array

4

In [47]:
first.size  # returns the total number of elements of the array

15

<font size="3">This (15) is equal to the product of the elements of ndarray.shape.</font>

### 1.e - Other

In [11]:
type(first)

numpy.ndarray

In [49]:
first.data  # the buffer containing the actual elements of the array

## 2- Array Creation

<font size="3">use **array** function in order to form an array by giving a regular Python list or tuple as an argument (a single sequence)</font>


In [13]:
new = np.array([1, 2, 3])

In [14]:
print(new)
print(type(new))
print(new.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int32


In [15]:
new_2 = np.array([1.0, 2.0, 3.0])
print(new_2.dtype)

float64


### 2.a - Two, Three... Dimensional Arrays

<font size="3">**array** function transforms sequences of sequences into **two-dimensional arrays**, sequences of sequences of sequences into **three-dimensional arrays**, and so on.
</font>

In [50]:
two_d = np.array([(1,2), (4,5), (7,8)])
print(two_d)
print("Dimensions:", two_d.ndim)
print("Size of dimensions:", two_d.shape)

print("-----------")

three_d = np.array([[(1, 2), (3, 4)], [(5, 6), (7, 8)]])
print(three_d)
print("Dimensions:", three_d.ndim)
print("Size of dimensions:", three_d.shape)

print("-----------")

another_3d = np.array([[(0, 1), (2, 3)], [(4, 5), (6, 7)], [(8, 9), (10, 11)]])
print(another_3d)
print("Dimensions:", another_3d.ndim)
print("Size of dimensions:", another_3d.shape)

[[1 2]
 [4 5]
 [7 8]]
Dimensions: 2
Size of dimensions: (3, 2)
-----------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Size of dimensions: (2, 2, 2)
-----------
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
Dimensions: 3
Size of dimensions: (3, 2, 2)


In [135]:
# investigate the output, not the code

line_break = "\n\n<<<<<<>>>>>>\n\n"
print("another_3d:\n", 
      another_3d, 
      line_break, 
      "another_3d[0]:\n", 
      another_3d[0],
      line_break,
      "another_3d[0][0]:\n",
      another_3d[0][0],
      line_break,
      "another_3d[0][0][0]:\n",
      another_3d[0][0][0])

another_3d:
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] 

<<<<<<>>>>>>

 another_3d[0]:
 [[0 1]
 [2 3]] 

<<<<<<>>>>>>

 another_3d[0][0]:
 [0 1] 

<<<<<<>>>>>>

 another_3d[0][0][0]:
 0


### 2.b - With 'dtype'

<font size="3">Specify your desired data type when creating an array with **dtype** argument</font>

In [51]:
print(np.array([1, 2, 3], dtype=complex), "\n\n", np.array([1, 2, 3], float))

[1.+0.j 2.+0.j 3.+0.j] 

 [1. 2. 3.]


### 2.c - Create Arrays With Initial Placeholder Content

In [52]:
print(np.zeros((2, 2)), end="\n\n")  # create an array full of zeros

print(np.ones((2, 3)), end="\n\n")  # create an array full of ones

# use 'empty' function to create an array whose initial content is random and depends on the state 
# of the memory. 'empty' function is marginally faster than 'zeros' function but should be used 
# with caution.
print(np.empty((3,2)), end="\n\n")

[[0. 0.]
 [0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]



<br> 

<font size="3">Use **zeros_like** function to return an array of zeros with the same shape and type as a given array.</font>

In [53]:
given_array = np.arange(1, 10, 4)
np.zeros_like(given_array)

array([0, 0, 0])

<br>

<font size="3">Use **ones_like** function to return an array of ones with the same shape and type as a given array</font>

In [54]:
np.ones_like(given_array)

array([1, 1, 1])

<br>

<font size="3">Use **empty_like** function to return a random array with the same shape and type as a given array.</font>

In [55]:
np.empty_like(given_array)

array([379251296,       565,         0])

### 2.d - 'arange' analogous to 'range'

<br>

<font size="3">Use **arange** function (analogous to the built-in function 'range') to create sequences of numbers.</font>

In [56]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [57]:
np.arange(1, 10, 1.5) # it accepts float arguments

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [58]:
# use 'linspace' function to return evenly spaced numbers over a specified interval:
np.linspace(1, 10, 9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [59]:
np.linspace(1, np.pi * 2, 100)

array([1.        , 1.05336551, 1.10673102, 1.16009652, 1.21346203,
       1.26682754, 1.32019305, 1.37355856, 1.42692407, 1.48028957,
       1.53365508, 1.58702059, 1.6403861 , 1.69375161, 1.74711711,
       1.80048262, 1.85384813, 1.90721364, 1.96057915, 2.01394465,
       2.06731016, 2.12067567, 2.17404118, 2.22740669, 2.2807722 ,
       2.3341377 , 2.38750321, 2.44086872, 2.49423423, 2.54759974,
       2.60096524, 2.65433075, 2.70769626, 2.76106177, 2.81442728,
       2.86779279, 2.92115829, 2.9745238 , 3.02788931, 3.08125482,
       3.13462033, 3.18798583, 3.24135134, 3.29471685, 3.34808236,
       3.40144787, 3.45481338, 3.50817888, 3.56154439, 3.6149099 ,
       3.66827541, 3.72164092, 3.77500642, 3.82837193, 3.88173744,
       3.93510295, 3.98846846, 4.04183396, 4.09519947, 4.14856498,
       4.20193049, 4.255296  , 4.30866151, 4.36202701, 4.41539252,
       4.46875803, 4.52212354, 4.57548905, 4.62885455, 4.68222006,
       4.73558557, 4.78895108, 4.84231659, 4.8956821 , 4.94904

## 3- Basic Operations

<font size="3">Arithmetic operators on arrays apply elementwise.</font>

In [157]:
tens = np.array([10, 20, 30, 40])
ones = np.arange(4)

the_sum = tens + ones
the_sum

array([10, 21, 32, 43])

In [158]:
ones ** 2

array([0, 1, 4, 9], dtype=int32)

In [159]:
np.sin(tens) * 10

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [160]:
tens < 25

array([ True,  True, False, False])

In [161]:
the_multip = ones * tens # elementwise product

the_multip

array([  0,  20,  60, 120])

In [162]:
matrix_a = np.array([[1, 0], [0, 1]])
matrix_b = np.array([[1, 3], [8, 7]])

matrix_a @ matrix_b # matrix product

matrix_a.dot(matrix_b) # another matrix product

array([[1, 3],
       [8, 7]])

### 3.a - Act in Place Operators

In [61]:
rg = np.random.default_rng(1) # create instance of default random number generator
matrix_a = rg.random((2, 2))
matrix_b = np.ones((2, 2), dtype=int)

# some operations, such as += and *=, act in place 
matrix_b *= 3
matrix_a += matrix_b

print("Matrix B:\n----\n", matrix_b)
print("\nMatrix A:\n----\n", matrix_a)

Matrix B:
----
 [[3 3]
 [3 3]]

Matrix A:
----
 [[3.51182162 3.9504637 ]
 [3.14415961 3.94864945]]


In [62]:
matrix_b += matrix_a # since matrix_a is not automatically converted to integer type, we'll get error
matrix_b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

### 3.b - Methods of ndarray Class As Unary Operations

<font size="3">Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.</font>

In [63]:
matrix_a = rg.random((2, 4))
print("Matrix\n----\n", matrix_a, 
      "\n Sum:", matrix_a.sum(), 
      "\n Minimum:", matrix_a.min(), 
      "\n Maximum:", matrix_a.max(), 
      "\n Cumulative Sum:\n", matrix_a.cumsum())

Matrix
----
 [[0.31183145 0.42332645 0.82770259 0.40919914]
 [0.54959369 0.02755911 0.75351311 0.53814331]] 
 Sum: 3.840868853982877 
 Minimum: 0.027559113243068367 
 Maximum: 0.8277025938204418 
 Cumulative Sum:
 [0.31183145 0.7351579  1.56286049 1.97205963 2.52165332 2.54921243
 3.30272554 3.84086885]


<br>

<font size="3">By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the **axis** parameter you can apply an operation along the specified axis of an array.</font>

In [64]:
matrix_a = np.arange(20).reshape(4, 5)
print("Matrix\n----\n", matrix_a, 
      "\n Sum of Each Column:", matrix_a.sum(axis=0), 
      "\n Minimum of Each Row:", matrix_a.min(axis=1), 
      "\n\n Cumulative Sum along Each Row:\n", matrix_a.cumsum(axis=1),
      "\n\n Cumulative Sum along Each Column:\n", matrix_a.cumsum(axis=0))

Matrix
----
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 
 Sum of Each Column: [30 34 38 42 46] 
 Minimum of Each Row: [ 0  5 10 15] 

 Cumulative Sum along Each Row:
 [[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]
 [15 31 48 66 85]] 

 Cumulative Sum along Each Column:
 [[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]]


### 3.c - Upcasting

<font size="3">When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).</font>

In [65]:
matrix_a = np.ones(3, dtype=int)
matrix_b = np.linspace(1, 10, 3)
matrix_a + matrix_b

array([ 2. ,  6.5, 11. ])

### 3.d - ufuncs (Universal Functions)

<font size="3">NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (**ufunc**). Within NumPy, these functions operate elementwise on an array, producing an array as output.</font>

In [66]:
a = np.arange(3)

np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [67]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356])

In [68]:
np.add(a, np.sqrt(a))

array([0.        , 2.        , 3.41421356])

In [69]:
a = np.arange(10).reshape(2, 5)
np.transpose(a)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [70]:
np.mean(a)

4.5

In [71]:
np.median(a)

4.5

In [72]:
np.std(a)

2.8722813232690143

In [73]:
np.var(a)

8.25

## 4- Indexing, Slicing and Iterating

In [74]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

<br>

<font size="4">**One-dimensional arrays** can be indexed, sliced and iterated over, much like lists and other Python sequences.</font>

In [75]:
a[1]

1

In [76]:
a[:3]

array([0, 1, 8], dtype=int32)

In [77]:
a[0:6:2]

array([ 0,  8, 64], dtype=int32)

In [78]:
a[:6:2] = 100
a

array([100,   1, 100,  27, 100, 125, 216, 343, 512, 729], dtype=int32)

In [79]:
a[::-1] # reversed a

array([729, 512, 343, 216, 125, 100,  27, 100,   1, 100], dtype=int32)

In [80]:
for i in a:
    if i > 100:
        print(i * (1 / 2))

62.5
108.0
171.5
256.0
364.5


<font size="3">**Quick Info**: *``fromfunction`` function constructs an array by executing a function over each coordinate. The resulting array therefore has a value ``fn(x, y, z)`` atcoordinate ``(x, y, z)``.*</font>

In [84]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [88]:
def f(x, y):
    return 10 * x + y

a = np.fromfunction(f, (5, 4), dtype=int)
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

<font size="3">**Multidimensional arrays** can have one index per axis. These indices are given in a tuple separated by commas.</font>

In [89]:
a[2, 3]

23

In [90]:
a[2]

array([20, 21, 22, 23])

In [95]:
a[:5, 1]  # each row in the second column of a

array([ 1, 11, 21, 31, 41])

In [96]:
a[:, 1]

array([ 1, 11, 21, 31, 41])

In [97]:
a[1:3, :]  # each column in the second and third row of a

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

<font size="3">When fewer indices are provided than the number of axes, the missing indices are considered complete slices:</font>

In [99]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [100]:
a[0]

array([0, 1, 2, 3])

In [101]:
a[-1]

array([40, 41, 42, 43])

In [102]:
a[0,:]

array([0, 1, 2, 3])

<font size="3">The expression within brackets in ``b[i]`` is treated as an ``i`` followed by as many instances of ``:`` as needed to represent the remaining axes. NumPy also allows you to write this using dots as ``b[i, ...]``. <br><br> The dots ``(...)`` represent as many colons as needed to produce a complete indexing tuple. </font>

In [115]:
print("a[0] ->     ", a[0],
      "\na[0, :] ->  ", a[0, :], 
      "\na[0, ...] ->", a[0, ...])

a[0] ->      [0 1 2 3] 
a[0, :] ->   [0 1 2 3] 
a[0, ...] -> [0 1 2 3]


In [120]:
# create a 3D array:
def f(x, y, z):
    return x * 100 + y * 10 + z

a3 = np.fromfunction(f, (2, 2, 3), dtype=int)
a3

array([[[  0,   1,   2],
        [ 10,  11,  12]],

       [[100, 101, 102],
        [110, 111, 112]]])

In [122]:
a3.shape

(2, 2, 3)

In [125]:
a3[0, ...]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [127]:
a3[..., 1]

array([[  1,  11],
       [101, 111]])

<font size="3">**Iterating** over multidimensional arrays is done with respect to the first axis:</font>

In [130]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [132]:
for row in a:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


<font size="3">However, if you want to perform an operation on each element in the array, you can use the ``flat`` attribute which is an **iterator** over all the elements of the array:</font>

In [133]:
for element in a.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
